name: Python Test

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
    tags:
      - 'v*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up .NET SDK
      uses: actions/setup-dotnet@v4.0.1
      with:
        dotnet-version: 8.0.x
    - name: Check dotnet version
      run: dotnet --version
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: 'microsoft' 
        java-version: '21'
    - name: Setup Maven Action
      uses: s4u/setup-maven-action@v1.12.0
      with:
        java-version: 21
        maven-version: '3.9.6'
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11.1
    - name: Get CloudNative.CloudEvents.Endpoint package code (java)
      uses: actions/checkout@v3
      with:
        repository: clemensv/io.cloudevents.experimental.endpoints
        ref: main
        path: javaendpoints
    - name: build CloudNative.CloudEvents.Endpoint package code
      run: mvn install -DskipTests -f javaendpoints/pom.xml
    - name: Install make
      run: sudo apt-get install -y make
    - name: Install dependencies and build package
      run: |
        python -m pip install --upgrade pip build wheel
        python -m pip install -e .
        python -m build --sdist --wheel --outdir dist
    - name: Install Test Prerequesites
      run: |
        npm install -g azure-functions-core-tools@4 --unsafe-perm true 
        npm install -g @asyncapi/cli
        npm install -g @openapitools/openapi-generator-cli      
    # unclear test hang inside the Github runner
    # - name: Run tests
    #   run: |
    #     pytest

